config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, expect: [:index] do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  resources :users, only: [:show, :edit, :update] do
    
  end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true

end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1' },
    { id: 3, name: '2' },
    { id: 4, name: '3' },
    { id: 5, name: '4' },
    { id: 6, name: '5' },
    { id: 7, name: '6' },
    { id: 8, name: '7' },
    { id: 9, name: '8' },
    { id: 10, name: '9' },
    { id: 11, name: '10' },
    { id: 12, name: '11' },
    { id: 13, name: '12' },
    { id: 14, name: '13' },
    { id: 15, name: '14' },
    { id: 16, name: '15' },
    { id: 17, name: '16' },
    { id: 18, name: '17' },
    { id: 19, name: '18' },
    { id: 20, name: '19' },
    { id: 21, name: '20' },
    { id: 22, name: '21' },
    { id: 23, name: '22' },
    { id: 24, name: '23' },
    { id: 25, name: '24' },
    { id: 26, name: '25' },
    { id: 27, name: '26' },
    { id: 28, name: '27' },
    { id: 29, name: '28' },
    { id: 30, name: '29' },
    { id: 31, name: '30' },
    { id: 32, name: '31' },
  ]

  include ActiveHash::Associations
  has_many :posts

  end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id    # バリデーション（ユーザーと記事の組み合わせは一意）
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1' },
    { id: 3, name: '2' },
    { id: 4, name: '3' },
    { id: 5, name: '4' },
    { id: 6, name: '5' },
    { id: 7, name: '6' },
    { id: 8, name: '7' },
    { id: 9, name: '8' },
    { id: 10, name: '9' },
    { id: 11, name: '10' },
    { id: 12, name: '11' },
    { id: 13, name: '12' }
  ]

  include ActiveHash::Associations
  has_many :posts

  end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :user
    # has_many :users, through: :favorites
    belongs_to :team
    belongs_to :month
    belongs_to :day
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    # has_many :post_tags
    # has_many :post_tags,through: :post_tags
    has_one_attached :image

    validates :month_id, numericality: { other_than: 1 , message: "は---以外を入力してください"}
    validates :day_id, numericality: { other_than: 1 , message: "は---以外を入力してください"}
    validates :content, presence: true, length: { maximum: 1000 }
    validates :image, presence: true

    def self.search(search)
      if search != ""
        Post.where('content LIKE(?)', "%#{search}%")
      else
        Post.all
      end
    end
    
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '横浜Fマリノス' },
    { id: 3, name: '川崎フロンターレ' },
    { id: 4, name: 'サンフレッチェ広島' },
    { id: 5, name: '鹿島アントラーズ' },
    { id: 6, name: 'セレッソ大阪' },
    { id: 7, name: 'FC東京' },
    { id: 8, name: '柏レイソル' },
    { id: 9, name: '名古屋グランパスエイト' },
    { id: 10, name: '浦和レッドダイヤモンズ' },
    { id: 11, name: '北海道コンサドーレ札幌' },
    { id: 12, name: 'サガン鳥栖' },
    { id: 13, name: '湘南ベルマーレ' },
    { id: 14, name: 'ヴィッセル神戸' },
    { id: 15, name: 'アビスパ福岡' },
    { id: 16, name: 'ガンバ大阪' },
    { id: 17, name: '京都サンガ' },
    { id: 18, name: '清水エスパルス' },
    { id: 19, name: 'ジュビロ磐田' },
    { id: 20, name: '日本代表ナショナルチーム' }
  ]

  include ActiveHash::Associations
  has_many :users

  end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :team
    has_many :comments
    has_many :posts
    has_many :favorites    

    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX}
    validates :nickname, presence: true
    validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/}
    validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/}

    def favorite_find(post_id)
        favorites.where(post_id: post_id).exists?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :team_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id]) #追加

    if @comment.save
      CommentChannel.broadcast_to @post, { comment: @comment, user: @comment.user } #追加
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    Favorite.create(user_id: current_user.id, post_id: params[:id])
    redirect_to post_path
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:id])
    favorite.destroy
    redirect_to post_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  before_action :move_to_index, except: [:index, :show, :search]


  def index
    @post = Post.all.order(id: :DESC)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end  
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end  
  end

  def search
    @post = Post.search(params[:keyword])
    @post.count

  end

  private

  def post_params
    params.require(:post).permit(:month_id, :day_id, :team_id, :content, :image ).merge(user_id: current_user.id)
  end

  def contributor_confirmation
    @post = Post.find(params[:id])
     unless current_user == @post.user
      redirect_to root_path
     end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @posts = current_user.posts

    @user = User.find(params[:id])
    @posts = @user.posts

    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)  # ログイン中のユーザーのお気に入りのpost_idカラムを取得
    @favorite_list = Post.find(favorites)     # postsテーブルから、お気に入り登録済みのレコードを取得
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if post.liked_by?(current_user) %>
   <%= link_to(post_add_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
       <i class="fa-lg fas fa-heart icon-btn liked"></i>
   <% end %>
<% else %>
   <%= link_to(post_add_path(post), method: :post, remote: true, id: :"like-button-#{post.id}") do %>
       <i class="fa-lg fas fa-heart icon-btn not-like"></i>
   <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "favorites/favorite", locals: { post: @post }) %>");

app/views/favorites/destroy.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "favorites/favorite", locals: { post: @post }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Go!Futbol!</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "item-sample.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "商品名" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= '999,999,999' %></p>
          <p class='item-price-sub-text'><%= '配送料負担' %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= "販売価格" %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :hoge, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :hoge, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/posts/_side_bar.html.erb
<div class="side-bar-wrapper">

 
  <style>
	.sample_menu_outer {
		margin: 4rem auto;
		}
	.sample_menu {
		width: 300px;
		padding: 10px 20px;
		}
	.sample_menu_parent {
		background-color: white;
		cursor: pointer;
		}
	.sample_menu_parent::before {
		content: '▼';
		display: inline-block;
		transform: rotate(-90deg);
		transition: .4s;
		}
	.sample_menu_parent.active::before {
		transform: rotate(0deg);
		}
	.sample_menu_child {
		color: white;
		height: 0;
		opacity: 0;
		visibility: hidden;
		transition: .4s;
		}
	.sample_menu_child.active {
		height: 2rem;
		opacity: 1;
		visibility: visible;
		}
	</style>
	
	<div class="sample_menu_outer">
		<ul>
			<li class="sample_menu sample_menu_parent">MENU</li>
			  <li class="sample_menu sample_menu_child">
         <div class="side-bar-container">
  <div class="side-bar-box">
    <%= image_tag "ホームアイコン.png", class:"side-bar-icon" %>
    <%= link_to "ホーム", root_path, class: "side-bar-item" %>
  </div>
  </div>
  <%# <div class="side-bar-container">
  <div class="side-bar-box">
     <%= image_tag "虫眼鏡の無料アイコン10.png", class:"side-bar-icon" %>
     <%# <%= link_to "検索", "#", class: "side-bar-item" %> 
  <%# </div> %>
  <%# </div> %> 
  <div class="side-bar-container">
  <div class="side-bar-box">
     <%= image_tag "星アイコン8.png", class:"side-bar-icon" %>
     <%# <%= link_to "お気に入り", "/users/#{current_user.id}", class: "side-bar-item" %> 
     <%= link_to "お気に入り", "#", class: "side-bar-item" %>

  </div>
  </div>
  <div class="side-bar-container">
  <div class="side-bar-box">
     <%= image_tag "カメラのアイコン素材 7.png", class:"side-bar-icon" %>
     <%= link_to '新規投稿', new_post_path, class: "side-bar-item"%>
  </div>
  </div>
  </li>
		</ul>
	</div>

	<script>
		{
			const sampleMenuP = document.querySelector('.sample_menu_parent');
			const sampleMenuC = document.querySelector('.sample_menu_child');

				sampleMenuP.addEventListener('click', () => {
				sampleMenuC.classList.toggle('active');
  				sampleMenuP.classList.toggle('active');
			});

		}
	</script>

  
</div>

app/views/posts/edit.html.erb
<div class="items-sell-contents">
  <header>
<%= render "shared/second-header"%>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿内容を入力</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像選択
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>

       <%# 投稿詳細選択 %>
       <div class="new-post-info">月を選択してください<span class="indispensable">必須</span></div>
        <%= f.collection_select(:month_id, Month.all, :id, :name , {}, {class:"select-box", id:"month-id"}) %>
       <div class="new-post-info">日を選択してください<span class="indispensable">必須</span></div>
        <%= f.collection_select(:day_id, Day.all, :id, :name , {}, {class:"select-box", id:"day-id"}) %>
       <div class="new-post-info">対戦チームを選択してください</div>
        <%= f.collection_select(:team_id, Team.all, :id, :name, {}, {class:"select-box", id:"team-id"})%>
       <%# 投稿詳細選択 %>

    <div class="new-items">

      <div class="items-explain">
        <div class="weight-bold-text">
          テキスト
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"投稿内容のコメントを（必須 1,000文字まで）
例）カタールワールドカップ決勝トーナメント一回戦vsクロアチア！スコアレスドローのまま延長30分でも決着がつかず、勝敗はPK戦へ。。。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer>
    <%= render "shared/second-footer"%>
  </footer>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="main_wrapper">
<div class="side_ber">
    <%= render "side_bar" %>
</div>




<div class="main">
 <div class="main-container"><div class="main-container-message">自分だけの特別な一枚<br>あの感動を共有しよう</div>
</div>

<div class="new-posts">PICK UP POST</div>
  <div class="image-list">
    <% @post.each do |post|%> 
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.image.variant(resize: '400x319',gravity: "center", crop: "300x250+0+0"), class: "post-image" %>
      <% end %>
      <%# <%= post.user.nickname%>
    <% end %>
  </div>
</div>
</div>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="main_wrapper">
<div class="side_ber">
    <%= render "side_bar" %>
</div>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">

        <div class="name">
      <%= "#{@post.user.nickname}'s post!" %>
        </div>

    <div class="item-img-content">
      <%= image_tag @post.image ,class:"item-box-img" %>
    </div>

    <% if current_user == @post.user%>
      <%= link_to "編集", edit_post_path, method: :get, class: "item-red-btn" %>
      <%= link_to "削除", post_path, method: :delete, class:"item-destroy" %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @post.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">日付</th>
          <td class="detail-value"><%= "#{@post.month.name}月""#{@post.day.name}日" %></td>
        </tr>
        <tr>
          <th class="detail-item">VS</th>
          <td class="detail-value"><%= "#{@post.team.name}戦" %></td>
        </tr>
        <tr>
          <th class="detail-item">コメント</th>
          <td class="detail-value"><%= @post.content%></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
        <%# <span>お気に入り 0</span> %>

       <%# お気に入り機能実装 %>
  <% if user_signed_in? && current_user !=@post.user %>
     <div class="favorite-btn">

    <% if current_user.favorite_find(@post.id) %>
      <%= image_tag "星アイコン6.png" ,class:"favorite-star-icon" ,width:"20",height:"20" %>
      <%= link_to 'お気に入りからはずす', destroy_favorite_path(@post.id), method: :delete, class: "favorite_status"%>
    <% else %>
      <%= image_tag "星アイコン8.png" ,class:"favorite-star-icon" ,width:"20",height:"20" %>
      <%= link_to 'お気に入り登録する', create_favorite_path(@post.id), method: :post, class: "favorite_status" %>
    <% end %>
  <% end %>
       <%# お気に入り機能実装 %>

      </div>
    </div>
  </div>
  <%# /商品の概要 %>

 
  <%# コメント機能の実装 %>
  
 <div class="comment-box"> 
   <h4>＜コメント一覧＞</h4>

<% if @comments.length == 0 %>
   <h4>コメントはありません</h4>
   <% else %>
  <div class="comments">
  <div id="comments">
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <p class="user-info"><%= comment.user.nickname %>： </p>
        <p><%= comment.text%></p>
        <%# <p><%= comment.created_at.to_s(:datetime_jp)</p>  %>
      </div>
    <% end %>
  </div>
  </div>
<% end %>

  <% if user_signed_in? %>
    <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>
        <%# <%= render 'shared/error_messages', model: f.object %> 
      <%= f.text_area :text , class: "comment-text"%>
      <div class="comment-index">
      <%= f.submit "コメントをする", class: "comment-btn" %>
      </div>
    <% end %>
  <% end %>
 </div> 
  <%# コメント機能の実装 %>
  
  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <%= link_to"#{@post.user.nickname}の投稿をもっと見る", "/users/#{current_user.id}",class: "another-item" %>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>
</div>

<%= render "shared/footer" %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to 'Go!Futbol!', root_path, class:"app_logo"%>
    <%= image_tag "トロフィー.png", class:"トロフィーicon" %>
<%# 検索フォーム %>
    <%# <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
      <img class="search-icon" 
        <%= image_tag "search.png", class:"search-icon" %>
      <%# </button> %>
    <%# </form> %>

    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "キーワードから探す", class: "input-box" %>
  <%= form.submit "検索", class: "search-button" %>
<% end %>
<%# 検索フォーム %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
    </ul>
    <ul class='lists-right'>
     <% if user_signed_in? %>      
      <li class="login-user"><%="LOGIN USER : "%>
        <%= link_to "#{current_user.nickname}", "/users/#{current_user.id}", class: "user-nickname" %>
      </li>
      <li><%= link_to "マイページ", "/users/#{current_user.id}", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
     <% elsif %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "logout" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "logout" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="main_wrapper">
<div class="side_ber">
    <%= render "posts/side_bar" %>
</div>
<div class="main">
<%# 個人詳細 %>
<div class="mypage_info">
  <div class="mypage_box">
    <div class="mypage_culumn">ニックネーム</div>
    <div class="mypage_value"><%= @user.nickname%></div>
  </div>
  <div class="mypage_box">
    <div class="mypage_culumn">好きなチーム</div>
    <div class="mypage_value"><%= @user.team.name%></div>
  </div>
</div>
<%# 個人詳細 %>
  <p class="mypage-nickname"><%= @nickname %>さんの投稿一覧</p>

  <% if @posts.length == 0 %>
   <h4 class="search-h4"><%= @nickname %>さんの投稿はありません</h4>
   <% else %>
    <% @posts.each do |post| %>
        <%= link_to user_path(post.user.id) do %>
        <%= image_tag post.image.variant(resize: '600x400',gravity: "center", crop: "300x250+0+0"), class: "post-image" %>
        <p class="mypage-info"><%= " < 投稿日 >　#{post.created_at.strftime('%Y/%m/%d')}" %><%=" ：#{post.content}" %></p>
      <% end %>
    <% end %>
    <% end %>
      <p class="mypage-nickname"><%= @nickname %>さんのお気に入り一覧</p>
      <% if @favorite_list.length == 0 %>
        <h4 class="search-h4"><%= @nickname %>さんのお気に入りはありません</h4>
      <% else %>
    <% @favorite_list.each do |favorite| %>
        <%= link_to post_path(favorite.user.id) do %>
        <%= image_tag favorite.image.variant(resize: '600x400',gravity: "center", crop: "300x250+0+0"), class: "post-image" %>
        <p class="mypage-info"><%= " < 投稿日 >　#{favorite.created_at.strftime('%Y/%m/%d')}" %><%=" ：#{favorite.content}" %></p>
      <% end %>
    <% end %>
    <% end %>
</div>
</div>

<%= render "shared/footer" %>